spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 543292334954-nb5iras711iko0rbu8js817veogq0ae9.apps.googleusercontent.com
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  datasource:
    url: jdbc:mysql://localhost:3306/ssd
    username: root
    password: 'kavindya123'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    show-sql: true
    ddl-auto: update
  server:
    port: 8081

app:
  tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
  tokenExpirationMsec: 864000000
  authorizedRedirectUris:
    - http://localhost:3000/oauth2/redirect
