
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssd
    username: root
    password: 'kavindya123'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    show-sql: true
    ddl-auto: update
  server:
        port: 8081
#  kavindya123